default_title: "Mangez mieux, moins cher, luttez contre le gaspillage"
meta_description: "Achetez les surplus de plats du jour sous forme de boxes à emporter vendues à prix cassé"
meta_image: "media.png" # Une image dans votre dossier app/assets/images/

