meta_title: "Mangez mieux, moins cher, luttez contre le gaspillage"
meta_description: "Achetez les surplus de plats de chefs forme de boxes à emporter vendues à prix cassé et luttez contre le gaspillage alimentaire ! Une box pour les chefs. "
meta_image: "facebook.jpg"

