default_title: "Mangez mieux, Moins cher, Luttez contre le gaspillage"
meta_description: "Achetez les surplus de plats du jour des restaurants à prix cassé"
meta_image: "logo.png" # Une image dans votre dossier app/assets/images/

